### ISSUE TITLE
Table heading inadequately describes where the Language Tags are used in content

### ISSUE THREAD

**Issue by radford-for-smpte** [sandflow/melt#11]
The second column heading [here](https://sandflow.github.io/melt/isdcf.html) reads:

> Language Tag for use in the CPL

It occurs to me that there are (at least) 4 places the Language Tag is used in a DCP:

1. CPL's `<Language>` element within Reels of type:
- MainSound
- MainSubtitle
- MainCaption
- ClosedCaption
- ClosedSubtitle
2. `<Language>` element with 428-7 DCST (Timed-Text XML)
3. Timed Text MXF (`RFC 5646 Language Tag List` of the Timed Text Descriptor)
4. Sound MXF (`RFC5646 Spoken Language`)

**Comment by palemieux** [comment]
Perhaps the table heading could simply say `RFC 5646 Language Tag`. We would then add a prolog explaining the use of the values in the table?

**Comment by radford-for-smpte** [comment]
Or “For use throughout the DCP” where that phrase is a link to the such a prolog?

**Comment by palemieux** [comment]
> “For use throughout the DCP”

Let's go for that now, and then we should plan on replace/update the prolog at https://isdcf.com/dcnc/home/appendix-1ab-language-codes.html
